collections:
  docs:
    output: true
    permalink: /docs/:path/
  web: 
    output: true
    permalink: /web/:path/
  emails:
    output: true
    permalink: /emails/:year/:month/:day/:path/
  pages:
    output: true
    permalink: /:path/


markdown: kramdown
